### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Parow** [FrazzIe/NativeUILua#19]
Hi, each time i open my menus i lost arround 2MiB

So it's boring because i have this warning 

http://prntscr.com/lr4lhw

**Comment by ImBaphomettt** [comment]
Can you send a complete `resmon 1` of your impacted resource ?

**Comment by Parow** [comment]
https://gyazo.com/1576397f46df133d1a805df02cac6cde by spamming menu

**Comment by ImBaphomettt** [comment]
It's really weird, I would say that it comes from your source code, because myself with a menu rather filled, I can not climb so high.

* Do not you have a while that inserts data in a loop ?
* This could possibly come from your menu opening system

If you allow me to look at your part of the code, I would surely find a solution.

**Comment by Parow** [comment]
Im recreating my menus everytime i open it because i have to refresh some datas

![image](https://user-images.githubusercontent.com/26217244/50481546-80392b80-09e2-11e9-8b03-2ea0e027a707.png)

**Comment by ImBaphomettt** [comment]
You should not re create them at every time the menu is open. this inevitably leads to performance problems.


Leave me the time to look how creates a function to refresh the menu without problem.

**Comment by Parow** [comment]
even if i keep the menu open there is some memories leaks

**Comment by Parow** [comment]
but less ram burned

**Comment by Parow** [comment]
I added u on discord, it can be easier to talk about this

**Comment by ImBaphomettt** [comment]
The problem is not memory leak, it’s just that you regenerate the menu in loop when it’s opened, it.
 
NativeUILua is not expected to have an updated loop display. 

I work on it to give it refresh functions without consuming ram/ CPU.  👍

i think you can close your issue. 🐞

but is not the issue the problems come for your code , you just want to use not correctly implements functions , the best way to fix this problems is to fork and modify NativeUI yourslef or wait people modify them.

ps (Look my forks / his update to view my modification) 🤟

Discord ID `Dylan M.#2135`

**Comment by Parow** [comment]
added u, thanks anyways im gonna work on it
